database/migrations/2020_04_10_001132_create_books_table.php

目的
・booksテーブル作成
実装
・.envファイル設定変更
・booksテーブル作成、マイグレーション

booksテーブル追加

---

routes/web.php

目的
・リソースフルルートでルート定義
実装
・resourceフルルートで一括定義
・indexアクションが既存ルーティングと被るのでexceptメソッドで除いた

リソースフルルートでルート定義

---

app/Http/Controllers/BookController.php
config/database.php
database/migrations/2014_10_12_000000_create_users_table.php
resources/views/app.blade.php

目的
・トップページ処理追加
実装
・BookControllerのダミーデータを削除
・booksテーブルから全データを取得する

トップページ処理追加

---

app/Http/Controllers/BookController.php

目的
・本の情報登録処理追加
実装
・登録画面へ遷移するcreateアクション
・登録処理を行うstoreアクションを追加
・登録後はトップページへリダイレクト

本の情報登録処理追加

---

database/migrations/2020_04_10_001132_create_books_table.php
database/seeds/BooksTableSeeder.php

目的
・DB関係ファイル修正
実装
・貸出状況を保持するstateカラムの型をbooleanからstringに変更
・貸出可能を"1"、貸出不可能を"2"としている
・phpの場合checkboxの値をstringとして扱うため

DB関係ファイル修正

---

resources/views/books/form.blade.php
resources/views/books/index.blade.php
resources/views/nav.blade.php

目的
・bladeファイル修正
実装
【form】
・name属性修正
・画像、貸出状況を送信できる仕様に変更
【index】
・labelとtextを【】で区別
・貸出状況はif文で表示変更
【nav】
・create.bladeへの遷移リンク追加

bladeファイル修正

---

app/Http/Controllers/BookController.php

目的
・更新日ごとに表示させる仕様変更
実装
・全ての情報を取り出して作成日ごとにsortをかける

作成日ごとに表示させる仕様変更

---

app/Http/Controllers/BookController.php
resources/views/books/index.blade.php

目的
・詳細画面表示機能追加
実装
・1つの情報だけcard.bladeとして作成
・タイトルを押下するとその本のcard画面に遷移

詳細画面表示機能追加

---

app/Book.php
resources/views/books/card.blade.php
resources/views/books/edit.blade.php
resources/views/books/show.blade.php

目的
・cardファイル作成
実装
・全てindexファイルに書くのは可読性が下がるためcard.bladeとして分割

cardファイル作成

---

app/Http/Controllers/Auth/RegisterController.php
app/Providers/RouteServiceProvider.php
resources/views/nav.blade.php
routes/api.php

目的
・ユーザー登録機能追加
実装
【RegisterController】
・ユーザー登録するバリデーション
【ServiceProvider】
・リダイレクト先を'/'に変更
【nav.blade】
・ログイン済みかどうかでnavタブの表示を変更する
【api.php】
・URIがapiから始まるルーティングを削除

ユーザー登録機能追加

---

resources/views/nav.blade.php

目的
・投稿画面遷移route修正
実装
・navタグにある「投稿する」の遷移リンクを修正

投稿画面遷移route修正

---

resources/views/books/create.blade.php
resources/views/books/edit.blade.php

目的
・エラー文表示機能追加
実装
・error文テンプレートをincludeで表示させる機能修正

エラー文表示機能追加

---

routes/web.php

目的
・ユーザー種別によるルート定義変更
実装
・未ログインユーザーが作成・更新・削除を実行できないようにルート定義を変更
・メイン・詳細は未ログインでも見ることができる

ユーザー種別によるルート定義変更

---

app/Http/Controllers/BookController.php
resources/views/books/card.blade.php
resources/views/books/detail.blade.php

#39　画像の表示修正

---

app/Http/Controllers/Admin/Auth/LoginController.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Providers/RouteServiceProvider.php
resources/views/auth/login.blade.php
resources/views/nav.blade.php

目的
・認証状態によるnavバーの表示方法を修正
・管理者認証関係修正
実装
・@ifではなく@auth@elseauthの方式に変更
・ログアウト後のリダイレクト先をnameで指定

Hotfix（#72）

---

database/migrations/2020_07_31_224727_drop_column_books_column.php
resources/views/books/card.blade.php
resources/views/books/detail.blade.php
resources/views/books/form.blade.php
routes/web.php

目的
・書籍card修正
・投稿更新削除機能を管理者に限定
実装
・booksテーブルstateカラム削除
・ユーザーの「予約できません」ボタン削除
・貸出状況ラジオボタン削除
・投稿更新削除機能に管理者ミドルウェアを付与
・詳細画面でも更新削除できるよう仕様に変更

Hotfix（#67）

---

app/Http/Controllers/UserController.php
app/User.php
resources/views/users/show.blade.php

ユーザーページ】予約履歴の表示機能作成 #46

---

app/Http/Controllers/BookingController.php
composer.json
composer.lock
resources/views/bookings/index.blade.php
resources/views/bookings/show.blade.php
resources/views/books/card.blade.php
resources/views/books/index.blade.php
resources/views/nav.blade.php
resources/views/users/index.blade.php
routes/web.php

目的
・管理側：予約申請一覧画面作成
実装
・申請一覧画面で申請と予約状況で一覧で表示
・未承認が上、承認済を下にソートして表示
・Laravel6では文字列や配列のヘルパはデフォルトから削除されたためcomposerインストール

予約申請一覧画面作成

---

app/Book.php
app/Http/Controllers/BookController.php
resources/sass/app.scss
resources/views/books/detail.blade.php

Feature(#43)

---

app/Booking.php
app/Http/Controllers/BookingController.php
app/Lending.php
database/migrations/2020_09_09_080208_create_lendings_table.php
public/css/app.css
public/mix-manifest.json
resources/views/bookings/show.blade.php
routes/web.php

【Add】貸出・返却ステータス更新機能追加
【要約】
貸出と返却もテーブルでデータ管理
【詳細】
lendingsテーブルを新規に作成
statusの値を追加して貸出中(status=2)と返却済(status=3)を管理
statusに応じて申請状況と予約詳細の表示を変更
貸出と返却はモーダルで一度確認

貸出・返却ステータス更新機能追加
